# Generated by Django 4.1.3 on 2023-02-04 15:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IR', unique=True)),
                ('age', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('birthday', models.DateField()),
                ('profileimage', models.ImageField(null=True, upload_to='', verbose_name='home/user/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
