# Generated by Django 4.1.3 on 2023-02-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_height_user_nationalcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
