# Generated by Django 4.1.3 on 2023-02-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
