# Generated by Django 4.1.3 on 2023-02-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_sports_user_program_sports_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sports',
            name='user',
        ),
        migrations.AddField(
            model_name='diet',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.program'),
            preserve_default=False,
        ),
    ]
