# Generated by Django 4.1.3 on 2023-02-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_remove_diet_user_remove_sports_user_diet_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sports',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='diet',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='diet',
        ),
        migrations.DeleteModel(
            name='sports',
        ),
    ]
