# Generated by Django 4.1.3 on 2023-02-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azmayesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='azmayesh',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='home/azmayesh/'),
            preserve_default=False,
        ),
    ]
