# Generated by Django 4.1.3 on 2023-02-15 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0004_manager_image_alter_manager_types'),
        ('user', '0003_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('price', models.BigIntegerField()),
                ('oprator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
            ],
        ),
        migrations.CreateModel(
            name='reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('accept', models.BooleanField()),
                ('types', models.CharField(choices=[('admin', 'admin'), ('Feeding', 'opratorF'), ('Wedding', 'opratorW'), ('Beauty', 'opratorB'), ('Photographic', 'opratorP'), ('Medical', 'opratorM'), ('Laboratory', 'opratorL'), ('Sports', 'opratorS')], max_length=20)),
                ('oprator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.manager')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
