# Generated by Django 4.1.3 on 2023-02-21 17:43

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='oprator_Laser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='IR', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='cortex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('descriptions', models.TextField()),
                ('numbermeet', models.IntegerField()),
                ('district', models.TextField()),
                ('oprator_Las', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cortex.oprator_laser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
