# Generated by Django 4.1.3 on 2023-02-21 18:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cortex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprator_laser',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IR', unique=True),
        ),
    ]
