# Generated by Django 4.1.3 on 2023-02-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_file_alter_post_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.CharField(choices=[('image', 'image'), ('podcast', 'podcast'), ('video', 'video')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
