# Generated by Django 4.1.3 on 2023-02-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_manager_image_alter_manager_types'),
        ('post', '0003_post_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='oprator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manager.manager'),
            preserve_default=False,
        ),
    ]
