# Generated by Django 4.1.3 on 2023-02-04 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='name',
            field=models.CharField(default='f', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
