# Generated by Django 4.1.3 on 2023-02-04 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_created_manager_name_manager_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='password',
        ),
    ]
