# Generated by Django 4.1.3 on 2023-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ravand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='home/ravand/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
