# Generated by Django 4.1.3 on 2023-02-04 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ravand', '0001_initial'),
        ('routin', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ravand',
            name='routin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routin.routin'),
        ),
        migrations.AddField(
            model_name='ravand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
